import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faBuildingColumns,
  faUserPen,
  faMagnifyingGlass,
  faPen,
  faCheckToSlot,
  faMoneyBillTrendUp,
} from '@fortawesome/free-solid-svg-icons';
import SEO from '../components/seo';
import Image from 'next/image';
import MainNavbar from '../components/Navbar';
import ScrollTopView from '../components/Scroller';
import FooterView from '../components/Footer';

export default function HowScinWorks() {
  return (
    <>
      <SEO
        title={'SCIN'}
        siteTitle={'How SCIN Works'}
        description={
          'SCIN is a decentralized scientific publishing platform, empowering researchers to retain the ownership of their work.'
        }
      />

      <MainNavbar />
      {/* <!-- ========================= hero-section start ========================= --> */}
      {/* ... other sections above */}

      {/* <!-- ========================= income-distribution-section start ========================= --> */}
      <section id="tracking" className="tracking-section pt-20">
        <div className="container">
          <div className="container row align-items-center">
            <div className="col-lg-6">
              <div className="tracking-content">
                <div
                  className="section-title mb-40"
                  style={{ marginRight: '2rem' }}
                >
                  <h1>Income Distribution*</h1>
                  <div className="text-styling mt-4">
                    At SCIN, we believe in fostering a collaborative and
                    equitable ecosystem for researchers, authors, institutions,
                    and all stakeholders involved in scholarly publishing. Our
                    income distribution model is designed to ensure fairness,
                    transparency, and sustainability in sharing the financial
                    benefits generated by our platform.
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-6">
              <div
                className="hero-img wow fadeInUp"
                data-wow-delay=".5s"
                style={{
                  borderRadius: '20px', // Add border radius
                  overflow: 'hidden', // Ensure the image follows the border radius
                  filter: 'drop-shadow(0 0 2rem rgba(0, 0, 0, 0.3))', // Add a fade effect
                }}
              >
                <Image
                  src="img/hero/1602186250-GettyImages-1150199386.jpg"
                  layout="responsive"
                  width={851}
                  height={601}
                  alt="Publishing Hero Image"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="income-distribution" className="pt-80 pb-40">
        <div className="container">
          <div className="row">
            {/* Authors */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body px-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faPen} />
                  </div>
                  <h4 className="card-title mt-2">Authors (28%)</h4>
                  <div className="text-styling pt-2">
                    Authors receive 28% of the total income for their
                    significant contribution to research creation.
                  </div>
                </div>
              </div>
            </div>
            {/* Affiliated Institutions */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body px-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faBuildingColumns} />
                  </div>
                  <h4 className="card-title mt-2">
                    Affiliated Institutions (18%)
                  </h4>
                  <div className="text-styling pt-2">
                    18% of the total income is allocated to the affiliated
                    institutions of authors.
                  </div>
                </div>
              </div>
            </div>
            {/* Reviewers */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body px-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faMagnifyingGlass} />
                  </div>
                  <h4 className="card-title mt-2">Reviewers (10%)</h4>
                  <div className="text-styling pt-2">
                    Reviewers receive 10% of the total income for their role in
                    ensuring the quality and integrity of published works.
                  </div>
                </div>
              </div>
            </div>
            {/* Editors */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body mx-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faUserPen} />
                  </div>
                  <h4 className="card-title mt-2">Editors (4%)</h4>
                  <div className="text-styling pt-2">
                    Editors, crucial in curating and overseeing the peer review
                    process, receive 4% of the total income.
                  </div>
                </div>
              </div>
            </div>
            {/* Proofreaders and Quality Control Personnel */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body mx-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faCheckToSlot} />
                  </div>
                  <h4 className="card-title mt-2">Typesetters (2%)</h4>
                  <div className="text-styling pt-2">
                    Proofreaders and quality control personnel are allocated 2%
                    of the total income for ensuring the accuracy and clarity of
                    research publications.
                  </div>
                </div>
              </div>
            </div>
            {/* SCIN */}
            <div className="col-md-4 mb-4 d-flex align-items-stretch">
              <div className="card shadow-lg">
                <div className="card-body px-5">
                  <div
                    className="pb-5 pt-4"
                    style={{ width: '2.5rem', height: '2.5rem' }}
                  >
                    <FontAwesomeIcon icon={faMoneyBillTrendUp} />
                  </div>
                  <h4 className="card-title mt-2">SCIN (38%)</h4>
                  <div className="text-styling pt-2">
                    SCIN allocates 38% of the total income to cover costs
                    associated with platform administration, maintenance, and
                    other operational expenses.
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container pt-4">
            * SCIN's goal is to achieve the mentioned numbers, but as a startup
            grows and evolves, these figures may change. When you publish with
            SCIN, you agree to the revenue distribution model in place at that
            time. These numbers are approximations and can be adjusted without
            legal consequences, with no liability for SCIN.
          </div>
        </div>
      </section>
      {/* <!-- ========================= income-distribution-section end ========================= --> */}

      {/* <!-- ========================= footer start ========================= --> */}
      <section id="home" className="container">
        {<FooterView />}
      </section>

      {/* <!-- ========================= scroll-top ========================= --> */}
      <ScrollTopView />
    </>
  );
}
