import Link from 'next/link';
import SEO from '../components/seo';
import Image from 'next/image';
import empoweringImage from '../../public/img/hero/1_j6TaV7aTIeTEH_z4o0MozA.jpg';
import Navbar from '../components/Navbar';
import ScrollTopView from '../components/Scroller';
import FooterView from '../components/Footer';

export default function HowScinWorks() {
  return (
    <>
      <SEO
        title={'SCIN'}
        siteTitle={'Decentralized Scientific Publishing'}
        description={
          'SCIN is a decentralized scientific publishing platform, empowering researchers to retain the ownership of their work.'
        }
      />

      <Navbar />
      {/* <!-- ========================= hero-section start ========================= --> */}
      {/* ... other sections above */}

      {/* <!-- ========================= income-distribution-section start ========================= --> */}
      <section id="tracking" className="tracking-section pt-150">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <div className="tracking-content">
                <div
                  className="section-title mb-50"
                  style={{ marginRight: '2rem' }}
                >
                  <h1 className="mt-5">Income Distribution</h1>
                  <p className="mt-5">
                    At SCIN, we believe in fostering a collaborative and
                    equitable ecosystem for researchers, authors, institutions,
                    and all stakeholders involved in scholarly publishing. Our
                    income distribution model is designed to ensure fairness,
                    transparency, and sustainability in sharing the financial
                    benefits generated by our platform.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-lg-6">
              <div
                className="hero-img wow fadeInUp"
                data-wow-delay=".5s"
                style={{
                  borderRadius: '20px', // Add border radius
                  overflow: 'hidden', // Ensure the image follows the border radius
                  filter: 'drop-shadow(0 0 2rem rgba(0, 0, 0, 0.3))', // Add a fade effect
                }}
              >
                <Image
                  src={empoweringImage}
                  layout="responsive"
                  width={851}
                  height={601}
                  alt="Publishing Hero Image"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="income-distribution" className="pt-150">
        <div className="container">
          <div className="row">
            {/* Authors */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-person-fill"></i> Authors (30%)
                  </h3>
                  <p className="card-text">
                    Authors receive 30% of the total income for their
                    significant contribution to research creation.
                  </p>
                </div>
              </div>
            </div>
            {/* Affiliated Institutions */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-building"></i> Affiliated Institutions
                    (20%)
                  </h3>
                  <p className="card-text">
                    20% of the total income is allocated to the affiliated
                    institutions of authors.
                  </p>
                </div>
              </div>
            </div>
            {/* Reviewers */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-clipboard-check"></i> Reviewers (9%)
                  </h3>
                  <p className="card-text">
                    Reviewers receive 9% of the total income for their role in
                    ensuring the quality and integrity of published works.
                  </p>
                </div>
              </div>
            </div>
            {/* Editors */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-pencil-square"></i> Editors (4%)
                  </h3>
                  <p className="card-text">
                    Editors, crucial in curating and overseeing the peer review
                    process, receive 4% of the total income.
                  </p>
                </div>
              </div>
            </div>
            {/* Proofreaders and Quality Control Personnel */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-card-checklist"></i> Proofreaders and QC
                    Personnel (2%)
                  </h3>
                  <p className="card-text">
                    Proofreaders and quality control personnel are allocated 2%
                    of the total income for ensuring the accuracy and clarity of
                    research publications.
                  </p>
                </div>
              </div>
            </div>
            {/* SCIN */}
            <div className="col-md-4 mb-4">
              <div className="card">
                <div className="card-body">
                  <h3 className="card-title">
                    <i className="bi bi-cash-stack"></i> SCIN (35%)
                  </h3>
                  <p className="card-text">
                    SCIN allocates 35% of the total income to cover costs
                    associated with platform administration, maintenance, and
                    other operational expenses.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* <!-- ========================= income-distribution-section end ========================= --> */}

      {/* <!-- ========================= footer start ========================= --> */}
      <section id="home" className="container">
        {<FooterView />}
      </section>

      {/* <!-- ========================= scroll-top ========================= --> */}
      <ScrollTopView />
    </>
  );
}
